### ISSUE TITLE
Errors in connect-imguraccont

### ISSUE THREAD

**Issue by itrmc** [1RedOne/PSImgur#1]
The following returned upon successful import and attempt to connect...

PS C:\Users\rollcast\Desktop\imgur> Connect-ImgurAccount -ClientID $myCID -clientSecret  $mySecret
Exception calling "SecureStringToCoTaskMemUnicode" with "1" argument(s): "Value cannot be null.
Parameter name: s"
At C:\Users\rollcast\Desktop\imgur\Public\Connect-ImgurAccount.ps1:71 char:9
-         $Ptr = [System.Runtime.InteropServices.Marshal]::SecureString ...
-         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  - CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
  - FullyQualifiedErrorId : ArgumentNullException

Cannot find an overload for "PtrToStringUni" and the argument count: "1".
At C:\Users\rollcast\Desktop\imgur\Public\Connect-ImgurAccount.ps1:72 char:9
-         $result = [System.Runtime.InteropServices.Marshal]::PtrToStri ...
-         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  - CategoryInfo          : NotSpecified: (:) [], MethodException
  - FullyQualifiedErrorId : MethodCountCouldNotFindBest

Cannot convert argument "s", with value: "", for "ZeroFreeCoTaskMemUnicode" to type "System.IntPtr": "Cannot convert
null to type "System.IntPtr"."
At C:\Users\rollcast\Desktop\imgur\Public\Connect-ImgurAccount.ps1:73 char:9
-         [System.Runtime.InteropServices.Marshal]::ZeroFreeCoTaskMemUn ...
-         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  - CategoryInfo          : NotSpecified: (:) [], MethodException
  - FullyQualifiedErrorId : MethodArgumentConversionInvalidCastArgument

Found cached Cred

Name                           Value

---

Imgur_username                 REDACTED

**Comment by 1RedOne** [comment]
This issue is fixed in the newest release.  I changed variables across the module but forgot one instance, which si precisely where this errored.  Good catch!

Please let me know that this fixed the issue in Connect-ImgurAccount.

**Comment by itrmc** [comment]
Great fix. Thanks.

**Comment by 1RedOne** [comment]
This has been resolved, thanks for finding it, @itrmc
