### ISSUE TITLE
get-content inefficient for some JPG images

### ISSUE THREAD

**Issue by itrmc** [1RedOne/PSImgur#2]
When using get-content on jpg files, some can run for what seems like an unlimited amount of time.  Consider using this line in new-imgurimage line 57 instead...

$image = [convert]::ToBase64String([System.IO.File]::ReadAllBytes($filepath))

**Comment by 1RedOne** [comment]
Wow, this is absurdly faster!

| Command | Milliseconds |
| --- | --- |
| Using Get-Content | 8482.152 |
| Using .net file reader | 2.4785 |

The only issue is having to resole the file full path ahead of time.  Do you wanna tackle this one?

**Comment by 1RedOne** [comment]
Integrated this in the latest release, thanks for finding a workaroudn.
